2.django-docker-example/django-boards/django_boards/rest/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from django_boards.rest.views import (CategoryViewSet, SubcategoryViewSet, ThreadViewSet,
    PostViewSet, ConversationViewSet, MessageViewSet, ShoutViewSet, UserViewSet,
    StatisticsView, obtain_auth_token)

router = routers.DefaultRouter()
router.register(r'categories', CategoryViewSet)
router.register(r'subcategories', SubcategoryViewSet)
router.register(r'threads', ThreadViewSet)
router.register(r'posts', PostViewSet)
router.register(r'conversations', ConversationViewSet)
router.register(r'messages', MessageViewSet)
router.register(r'shouts', ShoutViewSet)
router.register(r'users', UserViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^statistics/', StatisticsView.as_view(), name='statistics'),
    url(r'^auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^token-auth/', obtain_auth_token),
]

2.django-docker-example/django-boards/django_boards/urls.py
from django.conf.urls import url
import django.contrib.auth.views as auth_views

from django_boards.conf.settings import BOARD_THEME
from django_boards import views

app_name = 'board'

urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^unpermitted/$',
        views.unpermitted_view, name='unpermitted'),

    url(r'^register/$', views.registration_view, name='register'),
    url(r'^login/$',
        auth_views.login,
        {'template_name': 'django_boards/themes/{}/login.html'.format(BOARD_THEME)},
        name='login'),
    url(r'^logout/$',
        auth_views.logout, {'next_page': '/board/login/'}, name='logout'),
    url(r'^me/$', views.my_profile, name='me'),
    url(r'^settings/$', views.settings_view, name='settings'),
    url(r'^profile/(?P<username>[^/]+)/$', views.profile_view, name='profile'),

    url(r'^search/$', views.keyword_search_view, name='search'),

    url(r'^category/(?P<pk>[^/]+)/$',
        views.category_view, name='category'),
    url(r'^subcategory/(?P<pk>[^/]+)/$',
        views.subcategory_view, name='subcategory'),
    url(r'^thread/(?P<pk>[^/]+)/?$',
        views.thread_view, name='thread'),

    url(r'^inbox/$',
        views.conversations_list, name='inbox'),
    url(r'^conversation/(?P<pk>[^/]+)/$',
        views.conversation_view, name='conversation'),

    url(r'^create_thread/(?P<category_id>[^/]+)/$',
        views.thread_create, name='thread-create'),
    url(r'^update_thread/(?P<pk>[^/]+)/$',
        views.thread_update, name='thread-update'),
    url(r'^delete_thread/(?P<pk>[^/]+)/$',
        views.thread_delete, name='thread-delete'),

    url(r'^update_post/(?P<pk>[^/]+)/$',
        views.post_update, name='post-update'),
    url(r'^delete_post/(?P<pk>[^/]+)/$',
        views.post_delete, name='post-delete'),

    url(r'^reports/$',
        views.reports_list, name='reports-list'),
    url(r'^report/(?P<pk>[^/]+)/',
        views.report_view, name='report'),
    url(r'^report_thread/(?P<thread>[^/]+)/$',
        views.report_create, name='report-thread'),
    url(r'^report_post/(?P<post>[^/]+)/$',
        views.report_create, name='report-post'),

    url(r'^members/$',
        views.members_list, name='members-list'),

    url(r'^statistics/$',
        views.statistics_view, name='statistics'),

    url(r'^notification_redirect/(?P<pk>[^/]+)/$',
        views.notification_redirect, name='notification-redirect'),
]

2.django-docker-example/django-boards/example_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^board/', include('django_boards.urls')),
    url(r'^board/page/', include('django_boards.page_urls')),
    url(r'^board/api/', include('django_boards.rest.urls')),
    url(r'^captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

2.django-docker-example/django-boards/django_boards/rest/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from rest_framework import viewsets, permissions, mixins, views
from rest_framework.authentication import SessionAuthentication
from rest_framework.authtoken.models import Token
from rest_framework.authtoken.views import ObtainAuthToken as OriginalObtain
from rest_framework.decorators import list_route
from rest_framework.response import Response

from django_boards.models import (Category, Subcategory, Thread, Post, Conversation, Message,
    Report, Shout)
from django_boards.rest.serializers import (CategorySerializer, SubcategorySerializer,
    ThreadSerializer, PostSerializer, MessageSerializer, ShoutSerializer,
    ConversationSerializer, UserSerializer)
from django_boards.rest.permissions import IsTargetUser, BelongsToUser
from django_boards import queries


class UserViewSet(mixins.RetrieveModelMixin,
                  mixins.UpdateModelMixin,
                  mixins.ListModelMixin,
                  viewsets.GenericViewSet):
    queryset = get_user_model().objects.order_by('username')
    serializer_class = UserSerializer
    permission_classes = (permissions.IsAuthenticated, IsTargetUser,)

    @list_route()
    def from_token(self, request, *args, **kwargs):
        token_string = request.query_params.get('token')
        if not token_string:
            return Response('Token query param required', status=400)
        token = get_object_or_404(Token, key=token_string)
        self.kwargs['pk'] = token.user_id
        user = self.get_object()
        return Response(self.get_serializer(user).data)


class ObtainAuthToken(OriginalObtain):
    def post(self, request):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        token, created = Token.objects.get_or_create(user=user)
        return Response({
            'token': token.key,
            'id': user.id
        })
obtain_auth_token = ObtainAuthToken.as_view()


class CategoryViewSet(mixins.RetrieveModelMixin,
                      mixins.ListModelMixin,
                      viewsets.GenericViewSet):
    queryset = Category.objects.order_by('order')
    serializer_class = CategorySerializer

    def get_queryset(self):
        if self.request.user.is_authenticated and self.request.user.profile.is_banned:
            return Category.objects.none()
        qs = self.queryset
        if not self.request.user.is_authenticated:
            qs = qs.filter(auth_req=False)
        return qs.all()


class SubcategoryViewSet(mixins.RetrieveModelMixin,
                         mixins.ListModelMixin,
                         viewsets.GenericViewSet):
    queryset = Subcategory.objects.order_by('order')
    serializer_class = SubcategorySerializer

    def get_queryset(self):
        if self.request.user.is_authenticated and self.request.user.profile.is_banned:
            return Subcategory.objects.none()
        qs = self.queryset
        if not self.request.user.is_authenticated:
            qs = qs.filter(auth_req=False, parent__auth_req=False)
        parent_id = self.request.query_params.get('parent_id')
        if parent_id:
            qs = qs.filter(parent__id=parent_id)
        return qs.all()


class ThreadViewSet(mixins.CreateModelMixin,
                    mixins.RetrieveModelMixin,
                    mixins.ListModelMixin,
                    mixins.UpdateModelMixin,
                    viewsets.GenericViewSet):
    queryset = Thread.objects.order_by('-created')
    serializer_class = ThreadSerializer
    permission_classes = (BelongsToUser,)

    def get_queryset(self):
        if self.request.user.is_authenticated and self.request.user.profile.is_banned:
            return Thread.objects.none()
        qs = self.queryset
        if not self.request.user.is_authenticated:
            qs = qs.filter(
                category__auth_req=False,
                category__parent__auth_req=False)
        subcategory_id = self.request.query_params.get('subcategory_id')
        if subcategory_id:
            qs = qs.filter(category__id=subcategory_id)
        return qs.all()

    def perform_create(self, serializer):
        if self.request.user.is_authenticated and self.request.user.profile.is_banned:
            return Thread.objects.none()
        serializer.save(user=self.request.user)


class PostViewSet(mixins.CreateModelMixin,
                  mixins.RetrieveModelMixin,
                  mixins.ListModelMixin,
                  mixins.UpdateModelMixin,
                  viewsets.GenericViewSet):
    queryset = Post.objects.order_by('-created')
    serializer_class = PostSerializer
    permission_classes = (BelongsToUser,)

    def get_queryset(self):
        if self.request.user.is_authenticated and self.request.user.profile.is_banned:
            return Post.objects.none()
        qs = self.queryset
        if not self.request.user.is_authenticated:
            qs = qs.filter(
                thread__category__auth_req=False,
                thread__category__parent__auth_req=False)
        return qs.all()

    def perform_create(self, serializer):
        if self.request.user.is_authenticated and self.request.user.is_banned:
            return Post.objects.none()
        serializer.save(user=self.request.user)


class ConversationViewSet(mixins.CreateModelMixin,
                          mixins.RetrieveModelMixin,
                          mixins.ListModelMixin,
                          mixins.UpdateModelMixin,
                          viewsets.GenericViewSet):
    queryset = Conversation.objects.all()
    serializer_class = ConversationSerializer
    permission_classes = (permissions.IsAuthenticated,)

    def get_queryset(self):
        if self.request.user.is_authenticated and self.request.user.profile.is_banned:
            return Conversation.objects.none()
        qs = self.queryset
        qs = qs.filter(users__in=[self.request.user])
        return qs.all()

    def perform_create(self, serializer):
        if self.request.user.is_authenticated and self.request.user.profile.is_banned:
            return Conversation.objects.none()
        serializer.save(user=self.request.user)


class MessageViewSet(mixins.CreateModelMixin,
                     mixins.RetrieveModelMixin,
                     mixins.ListModelMixin,
                     mixins.UpdateModelMixin,
                     viewsets.GenericViewSet):
    queryset = Message.objects.all()
    serializer_class = MessageSerializer
    permission_classes = (permissions.IsAuthenticated,)

    def get_queryset(self):
        if self.request.user.is_authenticated and self.request.user.profile.is_banned:
            return Message.objects.none()
        qs = self.queryset
        qs = qs.filter(conversation__users__in=[self.request.user])
        return qs.all()

    def perform_create(self, serializer):
        if self.request.user.is_authenticated and self.request.user.profile.is_banned:
            return Message.objects.none()
        serializer.save(user=self.request.user)


class ShoutViewSet(mixins.CreateModelMixin,
                   mixins.ListModelMixin,
                   viewsets.GenericViewSet):
    queryset = Shout.objects.all()[:25]
    serializer_class = ShoutSerializer

    def perform_create(self, serializer):
        if self.request.user.is_authenticated and self.request.user.profile.is_banned:
            return Shout.objects.none()
        serializer.save(user=self.request.user)


class StatisticsView(views.APIView):
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, format=None):
        total_posts = Post.objects.count()
        total_threads = Thread.objects.count()
        total_members = get_user_model().objects.count()
        posts_by_dow = queries.posts_by_dow()
        threads_by_dow = queries.threads_by_dow()
        threads_in_subcategories = queries.threads_in_subcategories()
        return Response({
            'total_posts': total_posts,
            'total_threads': total_threads,
            'total_members': total_members,
            'posts_by_dow': posts_by_dow,
            'threads_by_dow': threads_by_dow,
            'threads_in_subcategories': threads_in_subcategories
        })

2.django-docker-example/django-boards/django_boards/templates/django_boards/themes/punkweb/category_view.html
{% extends 'django_boards/themes/punkweb/base.html' %}
{% load static %}

{% block meta_description %}{{category.description.rendered|striptags|truncatewords:160}}{% endblock %}
{% block title %}{{category.name}}{% endblock %}


{% block content %}
<div class="pageHeader">
  <div class="djcontainer">
    <div class="pageHeader__flex">
      <div class="pageHeader__left">
        <div class="pageHeader__title">{{category.name}}</div>
      </div>
      <div class="pageHeader__right">
        <ul class="breadcrumb">
          <li><a href="{% url 'board:index' %}">Board</a></li>
          <li>{{category.name}}</li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="main">
  <div class="djcontainer">
    <div class="category__description">{{category.description.rendered}}</div>
    <div class="panel">
      <div class="panel__body">
        <table class="table full-width">
          <thead>
            <tr>
              <th class="align-left" width="40%">
                Subcategory
              </th>
              <th class="align-center" width="10%">
                Threads
              </th>
              <th class="align-center" width="10%">
                Posts
              </th>
              <th class="align-left hide-on-mobile" width="40%">
                Last Thread
              </th>
            </tr>
          </thead>
          <tbody>
            {% for sub in subcategories %}
            <tr>
              <td class="align-left">
                <div>
                  <a href="{% url 'board:subcategory' sub.obj.id %}">{{sub.obj.name}}</a>
                </div>
                <div>{{sub.obj.description.rendered}}</div>
                {% if sub.can_post %}
                <div>
                  <a href="{% url 'board:thread-create' sub.obj.id %}">
                    <i class="fa fa-plus-circle" aria-hidden="true"></i> Create Thread
                  </a>
                </div>
                {% endif %}
              </td>
              <td class="align-center">
                <div>{{sub.obj.thread_count}}</div>
              </td>
              <td class="align-center">
                <div>{{sub.obj.post_count}}</div>
              </td>
              <td class="align-left hide-on-mobile">
                {% if sub.obj.last_thread %}
                <div>
                  <a href="{% url 'board:thread' sub.obj.last_thread.id %}">
                    {{sub.obj.last_thread.title|truncatechars_html:50}}
                  </a>
                </div>
                <div>{{sub.obj.last_thread.created|date:"d M Y, g:i A"}}</div>
                <div>
                  by
                  <a href="{% url 'board:profile' sub.obj.last_thread.user.username %}">
                    {{sub.obj.last_thread.user.profile.rendered_username}}
                  </a>
                </div>
                {% else %}
                <div>No Threads</div>
                {% endif %}
                </td>
              </tr>
              {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

2.django-docker-example/django-boards/django_boards/templates/django_boards/themes/punkweb/index.html
{% extends 'django_boards/themes/punkweb/base.html' %}
{% load humanize %}
{% load static %}
{% load bbcode_tags %}

{% block title %}Index{% endblock %}

{% block content %}
<div class="main">
  <div class="djcontainer">
    {% if BOARD_SETTINGS.USER_BIRTHDAY_MESSAGE %}
    {% include 'django_boards/themes/punkweb/components/birthday/birthday.html' %}
    {% endif %}
    <div class="flexrow">
      <div class="flexcol" style="flex: 3;">
        {% for category in categories %}
        <a name="{{category.parent.name}}"></a>
        <div class="panel">
          <div class="panel__body">
            <table class="table full-width">
              <thead data-role="collapsible-toggle" data-key="index-category-{{category.parent.id}}">
                <tr>
                  <th class="align-left" width="40%">
                    <a href="{% url 'board:category' category.parent.id %}">{{category.parent.name}}</a>
                  </th>
                  <th class="align-center" width="10%">
                    Threads
                  </th>
                  <th class="align-center" width="10%">
                    Posts
                  </th>
                  <th class="align-left hide-on-mobile" width="30%">
                    Last Thread
                  </th>
                </tr>
              </thead>
              <tbody data-role="collapsible" data-key="index-category-{{category.parent.id}}">
                {% for child in category.children %}
                <tr>
                  <td class="align-left">
                    <div><a href="{% url 'board:subcategory' child.id %}">{{child.name}}</a></div>
                    <div>{{child.description.rendered}}</div>
                  </td>
                  <td class="align-center">
                    <div>{{child.thread_count}}</div>
                  </td>
                  <td class="align-center">
                    <div>{{child.post_count}}</div>
                  </td>
                  <td class="align-left hide-on-mobile">
                    {% if child.last_thread %}
                    <div>
                      <a href="{% url 'board:thread' child.last_thread.id %}">
                        {{child.last_thread.title|truncatechars_html:50}}
                      </a>
                    </div>
                    <div>{{child.last_thread.created|date:"d M Y, g:i A"}}</div>
                    <div>by
                      <a href="{% url 'board:profile' child.last_thread.user.username %}">
                        {{child.last_thread.user.profile.rendered_username}}
                      </a>
                    </div>
                    {% else %}
                    <div>No Threads</div>
                    {% endif %}
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        {% endfor %}
      </div>
      <div class="flexcol sidebar" style="flex: 1;">
        <div class="panel">
          <div class="panel__header" data-role="collapsible-toggle" data-key="index-recent-threads">
            <div class="panel__title">Recent Threads</div>
          </div>
          <div class="panel__body padding" data-role="collapsible" data-key="index-recent-threads">
            {% if recent_threads %}
            {% for thread in recent_threads %}
            <div class="clearMargin padding-bottom">
              <a href="{% url 'board:thread' thread.id %}">{{thread.title}}</a>
              <div>{{thread.created|naturaltime}}</div>
              <div>by
                <a href="{% url 'board:profile' thread.user.username %}">
                  {{thread.user.profile.rendered_username}}
                </a>
              </div>
            </div>
            {% endfor %}
            {% else %}
            No recent threads
            {% endif %}
          </div>
        </div>
        <div class="panel">
          <div class="panel__header" data-role="collapsible-toggle" data-key="index-recent-activity">
            <div class="panel__title">Recent Activity</div>
          </div>
          <div class="panel__body padding" data-role="collapsible" data-key="index-recent-activity">
            {% if recent_activity %}
            {% for thread in recent_activity %}
            <div class="clearMargin padding-bottom">
              <a href="{% url 'board:thread' thread.id %}">{{thread.title}}</a>
              <div>{{thread.modified|naturaltime}}</div>
              {% if thread.last_post.user %}
              <div>by
                <a href="{% url 'board:profile' thread.last_post.user.username %}">
                  {{thread.last_post.user.profile.rendered_username}}
                </a>
              </div>
              {% else %}
              <div>by
                <a href="{% url 'board:profile' thread.user.username %}">
                  {{thread.user.profile.rendered_username}}
                </a>
              </div>
              {% endif %}
            </div>
            {% endfor %}
            {% else %}
            No recent activity
            {% endif %}
          </div>
        </div>
        <div class="panel">
          <div class="panel__header" data-role="collapsible-toggle" data-key="index-staff-online">
            <div class="panel__title">Staff Online</div>
          </div>
          <div class="panel__body padding" data-role="collapsible" data-key="index-staff-online">
            <table>
              {% for user in staff_online %}
              <tr>
                <td>
                  <img src="{{user.profile.avatar_smallest}}" alt="">
                </td>
                <td>
                  <a href="{% url 'board:profile' user.username %}">{{user.profile.rendered_username}}</a>
                </td>
              </tr>
              {% empty %}
              <span>No staff members are online</span>
              {% endfor %}
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class="flexrow">
      <div class="flexcol" style="flex: 1;">
        <div class="panel">
          <div class="panel__header" data-role="collapsible-toggle" data-key="index-users-online">
            <div class="panel__title">Users Online</div>
          </div>
          <div class="panel__body padding" data-role="collapsible" data-key="index-users-online">
            {% for user in users_online %}
            <a href="{% url 'board:profile' user.username %}">{{user.profile.rendered_username}}</a>
            {% empty %}
            <span>No users are online</span>
            {% endfor %}
          </div>
        </div>
        <a name="statistics"></a>
        <div class="panel statisticsPanel">
          <div class="panel__header" data-role="collapsible-toggle" data-key="index-statistics">
            <div class="panel__title"><a href="{% url 'board:statistics' %}">Statistics</a></div>
          </div>
          <div class="panel__body padding" data-role="collapsible" data-key="index-statistics">
            <ul class="statisticsPanel__list">
              <li style="display: inline">Total posts {{total_posts}} •</li>
              <li style="display: inline">Total threads {{total_threads}} •</li>
              <li style="display: inline">Total members {{member_count}} •</li>
              {% if newest_member %}
              <li style="display: inline">
                Newest member
                <a href="{% url 'board:profile' newest_member.username %}">
                  {{newest_member.profile.rendered_username}}
                </a>
              </li>
              {% else %}
              <li style="display: inline">No members</li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extrascript %}
{{ block.super }}
{% if BOARD_SETTINGS.SHOUTBOX_ENABLED %}
<script src="{% static 'django_boards/js/shoutbox.js' %}"></script>
{% endif %}
{% endblock %}

2.django-docker-example/django-boards/django_boards/templates/django_boards/themes/punkweb/page_not_found.html
{% extends 'django_boards/themes/punkweb/base.html' %}
{% load static %}

{% block title %}Page Not Found{% endblock %}
{% block meta_description %}Requested page was not found{% endblock %}

{% block extrascript %}
<script src="{% static 'django_boards/js/navigate.js' %}"></script>
{% endblock %}

{% block content %}
<div class="main">
  <div class="djcontainer">
    <div class="flex flex__justify-center">
      <div class="panel">
        <div class="panel__header">
          <div class="panel__title">Not Found</div>
        </div>
        <div class="panel__body padding">
          <p>The page you have requested was not found, it may have been moved or deleted.</p>
          <button class="button pageBack"><i class="fa fa-arrow-left fa-fw"></i> Back</button>
          <a class="button" href="{% url 'board:index' %}"><i class="fa fa-home fa-fw"></i> Home</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

2.django-docker-example/django-boards/django_boards/templates/django_boards/themes/punkweb/post_update_form.html
{% extends 'django_boards/themes/punkweb/base.html' %}

{% block title %}Update Post{% endblock %}

{% block content %}
<div class="pageHeader">
  <div class="djcontainer">
    <div class="pageHeader__flex">
      <div class="pageHeader__left">
        <div class="pageHeader__title">Update Post</div>
      </div>
      <div class="pageHeader__right">
        <ul class="breadcrumb">
          <li><a href="{% url 'board:index' %}">Board</a></li>
          <li><a href="{% url 'board:category' obj.thread.category.parent.id %}">{{obj.thread.category.parent.name}}</a></li>
          <li><a href="{% url 'board:subcategory' obj.thread.category.id %}">{{obj.thread.category.name}}</a></li>
          <li><a href="{% url 'board:thread' obj.thread.id %}">Thread</a></li>
          <li>Update Post</li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="main">
  <div class="djcontainer">
    <div class="panel">
      <div class="panel__header">
        <div class="panel__title">Update {{obj}}</div>
      </div>
      <div class="panel__body padding">
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="button"><i class="fa fa-edit fa-fw"></i> Update</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

2.django-docker-example/django-boards/django_boards/templates/django_boards/themes/punkweb/report_view.html
{% extends 'django_boards/themes/punkweb/base.html' %}
{% block title %}Report{% endblock %}

{% block content %}
<div class="pageHeader">
  <div class="djcontainer">
    <div class="pageHeader__flex">
      <div class="pageHeader__left">
        <div class="pageHeader__title">Resolve Report</div>
      </div>
      <div class="pageHeader__right">
        <ul class="breadcrumb">
          <li><a href="{% url 'board:index' %}">Board</a></li>
          <li><a href="{% url 'board:reports-list' %}">Reports</a></li>
          <li>{{report.id}}</li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="main">
  <div class="djcontainer">
    <div class="panel">
      <div class="panel__header">
        <div class="panel__title">{{report}}</div>
      </div>
      <div class="panel__body padding">
        <div class="margin-bottom">
          {% if report.post %}<a class="button" href="{% url 'board:thread' report.post.thread.id %}?page={{report.post.page_number}}#p{{report.post.post_number}}"><i class="fa fa-link fa-fw"></i> Jump to post</a>
          {% elif report.thread %}<a class="button" href="{% url 'board:thread' report.thread.id %}"><i class="fa fa-link fa-fw"></i> Jump to thread</a>{% endif %}
        </div>
        <div class="margin-bottom">
          <h2>Reason for Report</h2>
          <hr class="hr" />
          {{report.reason}}
        </div>
        <div class="margin-bottom">
          <h2>{% if report.post %}Post{% elif report.thread %}Thread{% endif %} Content</h2>
          <hr class="hr" />
          {% if report.post %}{{report.post.content.rendered}}{% elif report.thread %}{{report.thread.content.rendered}}{% endif %}
          {% if not report.resolved %}
          <form method="post">
            {% csrf_token %}
            <div class="align-right">
              <button class="button-green" type="submit"><i class="fa fa-check fa-fw"></i> Mark as Resolved</button>
              {% if report.post %}
              <a class="button" href="{% url 'board:post-update' report.post.id %}"><i class="fa fa-edit fa-fw"></i> Update Post</a>
              <a class="button-red" href="{% url 'board:post-delete' report.post.id %}"><i class="fa fa-trash fa-fw"></i> Delete Post</a>
              {% elif report.thread %}
              <a class="button" href="{% url 'board:thread-update' report.thread.id %}"><i class="fa fa-edit fa-fw"></i> Update Thread</a>
              <a class="button-red" href="{% url 'board:thread-delete' report.thread.id %}"><i class="fa fa-trash fa-fw"></i> Delete Thread</a>
            {% endif %}
            </div>
          </form>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

2.django-docker-example/django-boards/django_boards/templates/django_boards/themes/punkweb/thread_create_form.html
{% extends 'django_boards/themes/punkweb/base.html' %}

{% block title %}Create Thread{% endblock %}
{% block meta_description %}Create a thread in {{subcategory.name}}{% endblock %}

{% block content %}
<div class="pageHeader">
  <div class="djcontainer">
    <div class="pageHeader__flex">
      <div class="pageHeader__left">
        <div class="pageHeader__title">Create Thread</div>
      </div>
      <div class="pageHeader__right">
        <ul class="breadcrumb">
          <li><a href="{% url 'board:index' %}">Board</a></li>
          <li><a href="{% url 'board:category' subcategory.parent.id %}">{{subcategory.parent.name}}</a></li>
          <li><a href="{% url 'board:subcategory' subcategory.id %}">{{subcategory.name}}</a></li>
          <li>Create Thread</li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="main">
  <div class="djcontainer">
    <div class="panel">
      <div class="panel__header">
        <div class="panel__title">Create New Thread</div>
      </div>
      <div class="panel__body padding">
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="button-green" type="submit"><i class="fa fa-pencil-alt fa-fw"></i> Post Thread</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

2.django-docker-example/django-boards/django_boards/templates/django_boards/themes/punkweb/thread_update_form.html
{% extends 'django_boards/themes/punkweb/base.html' %}

{% block title %}Update Thread{% endblock %}

{% block content %}
<div class="pageHeader">
  <div class="djcontainer">
    <div class="pageHeader__flex">
      <div class="pageHeader__left">
        <div class="pageHeader__title">Update Thread</div>
      </div>
      <div class="pageHeader__right">
        <ul class="breadcrumb">
          <li><a href="{% url 'board:index' %}">Board</a></li>
          <li><a href="{% url 'board:category' object.category.parent.id %}">{{object.category.parent.name}}</a></li>
          <li><a href="{% url 'board:subcategory' object.category.id %}">{{object.category.name}}</a></li>
          <li><a href="{% url 'board:thread' object.id %}">Thread</a></li>
          <li>Update</li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="main">
  <div class="djcontainer">
    <div class="panel">
      <div class="panel__header">
        <div class="panel__title">Update {{object.title}} by {{object.user.username}}</div>
      </div>
      <div class="panel__body padding">
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="button-green" type="submit"><i class="fa fa-edit fa-fw"></i> Update</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}