2.django-docker-example/django-boards/django_boards/rest/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from django_boards.rest.views import (CategoryViewSet, SubcategoryViewSet, ThreadViewSet,
    PostViewSet, ConversationViewSet, MessageViewSet, ShoutViewSet, UserViewSet,
    StatisticsView, obtain_auth_token)

router = routers.DefaultRouter()
router.register(r'categories', CategoryViewSet)
router.register(r'subcategories', SubcategoryViewSet)
router.register(r'threads', ThreadViewSet)
router.register(r'posts', PostViewSet)
router.register(r'conversations', ConversationViewSet)
router.register(r'messages', MessageViewSet)
router.register(r'shouts', ShoutViewSet)
router.register(r'users', UserViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^statistics/', StatisticsView.as_view(), name='statistics'),
    url(r'^auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^token-auth/', obtain_auth_token),
]

2.django-docker-example/django-boards/django_boards/urls.py
from django.conf.urls import url
import django.contrib.auth.views as auth_views

from django_boards.conf.settings import BOARD_THEME
from django_boards import views

app_name = 'board'

urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^unpermitted/$',
        views.unpermitted_view, name='unpermitted'),

    url(r'^register/$', views.registration_view, name='register'),
    url(r'^login/$',
        auth_views.login,
        {'template_name': 'django_boards/themes/{}/login.html'.format(BOARD_THEME)},
        name='login'),
    url(r'^logout/$',
        auth_views.logout, {'next_page': '/board/login/'}, name='logout'),
    url(r'^me/$', views.my_profile, name='me'),
    url(r'^settings/$', views.settings_view, name='settings'),
    url(r'^profile/(?P<username>[^/]+)/$', views.profile_view, name='profile'),

    url(r'^search/$', views.keyword_search_view, name='search'),

    url(r'^category/(?P<pk>[^/]+)/$',
        views.category_view, name='category'),
    url(r'^subcategory/(?P<pk>[^/]+)/$',
        views.subcategory_view, name='subcategory'),
    url(r'^thread/(?P<pk>[^/]+)/?$',
        views.thread_view, name='thread'),

    url(r'^inbox/$',
        views.conversations_list, name='inbox'),
    url(r'^conversation/(?P<pk>[^/]+)/$',
        views.conversation_view, name='conversation'),

    url(r'^create_thread/(?P<category_id>[^/]+)/$',
        views.thread_create, name='thread-create'),
    url(r'^update_thread/(?P<pk>[^/]+)/$',
        views.thread_update, name='thread-update'),
    url(r'^delete_thread/(?P<pk>[^/]+)/$',
        views.thread_delete, name='thread-delete'),

    url(r'^update_post/(?P<pk>[^/]+)/$',
        views.post_update, name='post-update'),
    url(r'^delete_post/(?P<pk>[^/]+)/$',
        views.post_delete, name='post-delete'),

    url(r'^reports/$',
        views.reports_list, name='reports-list'),
    url(r'^report/(?P<pk>[^/]+)/',
        views.report_view, name='report'),
    url(r'^report_thread/(?P<thread>[^/]+)/$',
        views.report_create, name='report-thread'),
    url(r'^report_post/(?P<post>[^/]+)/$',
        views.report_create, name='report-post'),

    url(r'^members/$',
        views.members_list, name='members-list'),

    url(r'^statistics/$',
        views.statistics_view, name='statistics'),

    url(r'^notification_redirect/(?P<pk>[^/]+)/$',
        views.notification_redirect, name='notification-redirect'),
]

2.django-docker-example/django-boards/example_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^board/', include('django_boards.urls')),
    url(r'^board/page/', include('django_boards.page_urls')),
    url(r'^board/api/', include('django_boards.rest.urls')),
    url(r'^captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

2.django-docker-example/django-boards/django_boards/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from easy_thumbnails.widgets import ImageClearableFileInput
from django_boards.conf.settings import BOARD_THEME, CAPTCHAS_ENABLED, SIGNATURES_ENABLED
from django_boards.models import Thread, Post, Shout, Report, Message
# from django_boards.models import EmailUser, Thread, Post, Shout, Report, Message


# class NewConversationForm(forms.Form):
#     def __init__(self, request, *args, **kwargs):
#         super(NewConversationForm, self).__init__(*args, **kwargs)
#
#     users_queryset = EmailUser.objects.exclude(is_banned=True)
#     subject = forms.CharField(max_length=140, initial='No subject')
#     users = forms.ModelMultipleChoiceField(queryset=users_queryset)
#     message = forms.CharField(
#         widget=forms.Textarea(attrs={'class': 'post-editor'}),
#         label=_('Message'),
#         required=True
#     )


class KeywordSearchForm(forms.Form):
    keyword = forms.CharField(max_length=80, required=True, label='')


class SettingsForm(forms.Form):
    def __init__(self, request, *args, **kwargs):
        super(SettingsForm, self).__init__(*args, **kwargs)
        self.fields['gender'].initial = request.user.profile.gender
        self.fields['birthday'].initial = request.user.profile.birthday
        if SIGNATURES_ENABLED:
            signature = forms.CharField(
                widget=forms.Textarea(attrs={'class': 'post-editor'}),
                label=_('Signature'),
                required=False,
                initial=request.user.profile.signature
            )
            self.fields['signature'] = signature

    GENDER_CHOICES = [
        ('', ''),
        ('f', 'Female'),
        ('m', 'Male'),
    ]
    image = forms.ImageField(
        label=_('Profile Image'),
        required=False
    )
    gender = forms.ChoiceField(
        choices=GENDER_CHOICES,
        label=_('Gender'),
        required=False
    )
    birthday = forms.DateField(
        label=_('Birthday (yyyy-mm-dd)'),
        required=False
    )


class RegistrationForm(forms.Form):
    username = forms.RegexField(
        regex=r'^\w+$',
        widget=forms.TextInput(attrs=dict(required=True, max_length=30)),
        label=_("Username"),
        error_messages={
            'invalid': _("This value must contain only letters, " \
                         "numbers and underscores.")
        }
    )
    email = forms.EmailField(
        widget=forms.TextInput(attrs=dict(required=True, max_length=30)),
        label=_("Email address")
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs=dict(required=True, max_length=30, render_value=False)),
        label=_("Password")
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs=dict(required=True, max_length=30, render_value=False)),
        label=_("Password (again)")
    )
    if CAPTCHAS_ENABLED:
        from captcha.fields import CaptchaField
        captcha = CaptchaField()

    def clean_username(self):
        try:
            user = get_user_model().objects.get(
                username__iexact=self.cleaned_data['username'])
        except get_user_model().DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_("The username already exists. " \
                                      "Please try another one."))

    def clean(self):
        if 'password1' in self.cleaned_data and \
           'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(
                    _("The two password fields did not match."))
        return self.cleaned_data


class ThreadForm(forms.ModelForm):
    def __init__(self, request, *args, **kwargs):
        super(ThreadForm, self).__init__(*args, **kwargs)
        self.request = request
        self.fields['content'].label = ''
        self.fields['content'].widget.attrs['class'] = 'post-editor'

    def save(self, category=None, commit=True, set_user=False):
        obj = super(ThreadForm, self).save(commit=False)
        if category:
            obj.category = category
        if set_user:
            obj.user = self.request.user
        if commit:
            obj.save()
        return obj

    class Meta:
        model = Thread
        fields = ['title', 'tags', 'content']


class PostForm(forms.ModelForm):
    def __init__(self, request, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.request = request
        self.fields['content'].label = ''
        self.fields['content'].widget.attrs['class'] = 'post-editor'

    def save(self, thread=None, commit=True, set_user=False):
        obj = super(PostForm, self).save(commit=False)
        if thread:
            obj.thread = thread
            obj.thread.modified = timezone.now()
            obj.thread.save()
        if set_user:
            obj.user = self.request.user
        if commit:
            obj.save()
        return obj

    class Meta:
        model = Post
        fields = ['content']


class ShoutForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ShoutForm, self).__init__(*args, **kwargs)
        self.fields['content'].label = ''
        self.fields['content'].widget.attrs['class'] = 'shout-editor'

    class Meta:
        model = Shout
        fields = ['content']


class ReportForm(forms.ModelForm):
    def __init__(self, request, *args, **kwargs):
        super(ReportForm, self).__init__(*args, **kwargs)
        self.request = request
        self.fields['reason'].label = 'Reason for report:'
        self.fields['reason'].widget.attrs['cols'] = '80'
        self.fields['reason'].widget.attrs['rows'] = '6'

    def save(self, thread=None, post=None, set_user=False, commit=True):
        obj = super(ReportForm, self).save(commit=False)
        if thread:
            obj.thread = thread
        if post:
            obj.post = post
        if set_user:
            obj.reporting_user = self.request.user
        if commit:
            obj.save()
        return obj

    class Meta:
        model = Report
        fields = ['reason']


class MessageForm(forms.ModelForm):
    def __init__(self, request, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        self.fields['content'].label = ''
        self.fields['content'].widget.attrs['class'] = 'post-editor'
        self.request = request

    def save(self, conversation=None, commit=True):
        obj = super(MessageForm, self).save(commit=False)
        obj.user = self.request.user
        if conversation:
            obj.conversation = conversation
        if commit:
            obj.save()
        return obj

    class Meta:
        model = Message
        fields = ['content']

2.django-docker-example/django-boards/django_boards/templates/django_boards/themes/punkweb/includes/footer.html
<footer class="footer">
  <div class="djcontainer">
    <div class="footer__content">
      <div>
        Powered by <a target="_blank" href="https://github.com/shakedown-street/django-boards">shakedown-street/django-boards</a>
      </div>
      <div>
        <a href="/board/api/"><i class="fa fa-terminal fa-fw"></i> API</a>
      </div>
    </div>
  </div>
</footer>

2.django-docker-example/django-boards/django_boards/templates/django_boards/themes/punkweb/includes/nav.html
{% load humanize %}
{% load static %}

<div class="nav nav--upper">
  <div class="nav__flex">
    <div class="nav__left">
      {% if user.is_authenticated %}
      {% if user.is_staff %}
      <a class="nav--upper__link" href="/admin/"><i class="fa fa-user-plus fa-fw" aria-hidden="true"></i> Admin</a>
      {% endif %}
      {% endif %}
    </div>
    <div class="nav__right">
      {% if user.is_authenticated %}
      {% if user.is_staff %}
      <a class="nav--upper__link" href="{% url 'board:reports-list' %}"><i class="fa fa-ban fa-fw" aria-hidden="true"></i> Reports {% if unresolved_reports > 0%}<span class="badge">{{unresolved_reports}}</span>{% endif %}</a>
      {% endif %}
      <a class="nav--upper__link" href="{% url 'board:inbox' %}"><i class="fa fa-inbox fa-fw" aria-hidden="true"></i> Inbox {% if unread_conversations > 0%}<span class="badge">{{unread_conversations}}</span>{% endif %}</a>
      <div class="nav--upper__link dropdown">
        <i class="fa fa-bell fa-fw" aria-hidden="true"></i> Notifications {% if unread_notifications > 0%}<span class="badge">{{unread_notifications}}</span>{% endif %}
        <div class="dropdown__content">
          {% for notification in notifications %}
          {% if notification.read %}
          <div class="notification">
            {% if notification.link %}
            <a href="{% url 'board:notification-redirect' notification.id %}">
              {{notification.text}}
            </a>
            {% else %}
            {{notification.text}}
            {% endif %}
            <br/>
            {{notification.created|naturaltime}}
          </div>
          {% else %}
          <div class="notification notification--unread">
            {% if notification.link %}
            <a href="{% url 'board:notification-redirect' notification.id %}">
              {{notification.text}}
            </a>
            {% else %}
            {{notification.text}}
            {% endif %}
            <br/>
            {{notification.created|naturaltime}}
          </div>
          {% endif %}
          {% endfor %}
        </div>
      </div>
      <a class="nav--upper__link" href="{% url 'board:me' %}"><i class="fa fa-user fa-fw" aria-hidden="true"></i> Account</a>
      <a class="nav--upper__link" href="{% url 'board:settings' %}"><i class="fa fa-cog fa-fw" aria-hidden="true"></i> Settings</a>
      {% block upper_right_links %}
      {% endblock %}
      <a class="nav--upper__link" href="{% url 'board:logout' %}"><i class="fa fa-sign-out-alt fa-fw" aria-hidden="true"></i> Logout</a>
      {% else %}
      <a class="nav--upper__link" href="{% url 'board:register' %}"><i class="fa fa-user-plus fa-fw" aria-hidden="true"></i> Sign up</a>
      <a class="nav--upper__link" href="{% url 'board:login' %}"><i class="fa fa-sign-in-alt fa-fw" aria-hidden="true"></i> Login</a>
      {% endif %}
    </div>
  </div>
</div>
<div class="nav nav--main">
  <div class="nav__flex">
    <div class="nav__left">
      <div class="nav__title"><a href="/">{{BOARD_SETTINGS.BOARD_NAME}}</a></div>
      <a class="nav__link" href="{% url 'board:index' %}">Forum</a>
      <a class="nav__link" href="{% url 'board:members-list' %}">Members</a>
    </div>
    <div class="nav__right">
      {% block main_right_links %}
      {% endblock %}
      <form action="/board/search/" method="get">
        <div class="search">
          <span class="fa fa-search fa-fw"></span>
          <input id="id_keyword" maxlength="80" name="keyword" type="text" placeholder="Search" required />
        </div>
      </form>
    </div>
  </div>
</div>

2.django-docker-example/django-boards/django_boards/templates/django_boards/themes/punkweb/includes/page_header.html
<div class="pageHeader">
  <div class="djcontainer">
    <div class="pageHeader__flex">
      <div class="pageHeader__left">
        <div class="pageHeader__title">{% block title %}{% endblock %}</div>
      </div>
      <div class="pageHeader__right">
        {% block breadcrumb %}{% endblock %}
      </div>
    </div>
  </div>
</div>